### PR TITLE
OLECNTRB-11 : Full location display in Rest API

### PR DESCRIPTION
**Pull request by SBRitter**
Displays full names of Location Level in addition to the code when using the Rest API. 

See https://jira.kuali.org/browse/OLECNTRB-11

### CODE REVIEW

**Comment by SBRitter** [comment]
True, the mappings in ojb-describe are redundant. Or do you mean: avoid reproducing the location and location level pojo inside the docstore module?

**Comment by julianladisch** [comment]
This improvement is fine with me because it does not affect the VuFind interface: https://github.com/gbv/vufind/tree/VuFind_2.4-VZG_OLE

**Comment by julianladisch** [comment]
New jira number: https://openlibraryenvironment.atlassian.net/browse/OLE-8610

**Comment by SBRitter** [comment]
Peri, do you need more information or changes to the code? Let me know.

**Comment by peris** [comment]
Simon, seems like the pull request has some conflicts. Could you please take a look at it. Can you re-create the pull request on the latest code?

**Pull request closed without merging**
